# Generated by Django 4.2.16 on 2024-10-23 00:58

import cadastro_pet.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('idade', models.PositiveIntegerField()),
                ('raca', models.CharField(default='Viralata', max_length=75)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('fêmea', 'Fêmea')], default='macho', max_length=10)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], default='cachorro', max_length=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('historico_saude', models.TextField(max_length=300)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Animal',
                'verbose_name_plural': 'Cadastro de Animais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=cadastro_pet.models.upload_to_image)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='cadastro_pet.cadastroanimal')),
            ],
        ),
    ]
